docs_dir: docs

site_name: Nós 💚
site_url: https://viniciusfs14.github.io/contador/

theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: red
  font:
    text: "Roboto"
    code: "Courier New"
  icon:
    logo: fontawesome/solid/heart
    
nav:
  - Nós 💚: inicio.md
  - Linha: linha.md

extra_css:
  - styles/custom.css
  - assets/custom.css
  - assets/sara.css

extra_javascript:
  - js/contador.js
  

